Misc fix
cpuguy83/tarfs pull request #1
Opened 2018-04-14 03:51 UTC by AkihiroSuda

* Sirupsen -> sirupsen
* fix panic which had occurred when the archive does not contain the root
* add FromReaderAt

I'm considering using this library for mounting `vnd.oci.image.layer.v1.tar` blobs on the registry directly, without pulling the whole blob contents.

https://github.com/AkihiroSuda/filegrain/issues/21

@cpuguy83

2018-04-15 12:28 UTC, cpuguy83 requested changes
Looks like this needs to re-run dep to get the vendor udpated.

2018-04-15 12:28 UTC, cpuguy83 commented on fs.go
> +func FromReaderAt(ra io.ReaderAt, size int64, db MetadataStore) (pathfs.FileSystem, error) {
Can you add a doc string?

2018-04-15 12:28 UTC, cpuguy83 commented on fs.go
> +		Ino:  2, // follows traditional convention
Is there details on the convention somewhere?

2018-04-15 12:28 UTC, cpuguy83 commented on fs.go
> +			logrus.Warnf("no entry found for %q (parent of %q)", parentKey, key)
Maybe we should track these and error out later on any remaining empty nodes?
Since there is no specific ordering for the tar format this warning could come up frequently as a false positive.

Mostly I want to got rid of logrus, currently only using for debugging.

2018-04-16 02:56 UTC, AkihiroSuda commented
fixed, PTAL

2018-04-16 15:03 UTC, cpuguy83 commented on .gitignore
> -vendor
lol, no wonder I couldn't get these vendors to update before 😂

2018-04-16 15:06 UTC, cpuguy83 approved these changes
LGTM, thanks!

2018-04-16 15:06 UTC, merged